name: social_vrnn
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.10.0
  - astor=0.8.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.11.8
  - cairo=1.16.0
  - certifi=2020.11.8
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cycler=0.10.0
  - decorator=4.4.2
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.66.1
  - gmp=6.1.2
  - gnutls=3.6.13
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.30.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - importlib-metadata=3.1.0
  - intel-openmp=2020.2
  - jasper=2.0.14
  - jpeg=9d
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.0
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libtiff=4.1.0
  - libvpx=1.7.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markdown=3.3.3
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - mkl=2020.2
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.10.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - opencv=3.4.2
  - openh264=2.1.1
  - openssl=1.1.1h
  - opt_einsum=3.3.0
  - pcre=8.44
  - pip=20.2.4
  - pixman=0.38.0
  - progressbar=2.5
  - protobuf=3.12.3
  - py-opencv=3.4.2
  - pykalman=0.9.5
  - pyparsing=2.4.7
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.4.0
  - pytz=2020.4
  - readline=8.0
  - scipy=1.2.1
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - tensorflow-probability=0.7
  - termcolor=1.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.53.0
  - werkzeug=0.16.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - x264=1!157.20191217
  - xz=5.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5